#spring.application.name=service-product
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
server:
  port: 8093
  include-message: always


#http://localhost:8091/h2-console para ver la consola H2 en el navegador
spring:
  application:
    name: service-invoice
  sql:
    init:
      mode: always


  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
      